### ISSUE TITLE
no Go files

### ISSUE THREAD

**Issue by evandrix** [gravetii/diztl#9]
```
$ go get -u -v github.com/gravetii/diztl
github.com/gravetii/diztl (download)
package github.com/gravetii/diztl: no Go files in $HOMR/go/src/github.com/gravetii/diztl
```

**Comment by gravetii** [comment]
@evandrix Can you tell me what OS you're on? Also, can you just navigate to the directory if the files are there even though you see this message?

**Comment by gravetii** [comment]
Check updated instructions in README.
